/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsTrendsRouteImport } from './routes/reports.trends'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as ReportsDocumentsRouteImport } from './routes/reports.documents'
import { Route as ReportsDistributionRouteImport } from './routes/reports.distribution'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsTrendsRoute = ReportsTrendsRouteImport.update({
  id: '/reports/trends',
  path: '/reports/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsDocumentsRoute = ReportsDocumentsRouteImport.update({
  id: '/reports/documents',
  path: '/reports/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsDistributionRoute = ReportsDistributionRouteImport.update({
  id: '/reports/distribution',
  path: '/reports/distribution',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/reports/distribution': typeof ReportsDistributionRoute
  '/reports/documents': typeof ReportsDocumentsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/trends': typeof ReportsTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/reports/distribution': typeof ReportsDistributionRoute
  '/reports/documents': typeof ReportsDocumentsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/trends': typeof ReportsTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/reports/distribution': typeof ReportsDistributionRoute
  '/reports/documents': typeof ReportsDocumentsRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/trends': typeof ReportsTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/settings'
    | '/team'
    | '/reports/distribution'
    | '/reports/documents'
    | '/reports/sales'
    | '/reports/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/inbox'
    | '/settings'
    | '/team'
    | '/reports/distribution'
    | '/reports/documents'
    | '/reports/sales'
    | '/reports/trends'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/inbox'
    | '/settings'
    | '/team'
    | '/reports/distribution'
    | '/reports/documents'
    | '/reports/sales'
    | '/reports/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  InboxRoute: typeof InboxRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  ReportsDistributionRoute: typeof ReportsDistributionRoute
  ReportsDocumentsRoute: typeof ReportsDocumentsRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  ReportsTrendsRoute: typeof ReportsTrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/trends': {
      id: '/reports/trends'
      path: '/reports/trends'
      fullPath: '/reports/trends'
      preLoaderRoute: typeof ReportsTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/documents': {
      id: '/reports/documents'
      path: '/reports/documents'
      fullPath: '/reports/documents'
      preLoaderRoute: typeof ReportsDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/distribution': {
      id: '/reports/distribution'
      path: '/reports/distribution'
      fullPath: '/reports/distribution'
      preLoaderRoute: typeof ReportsDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  InboxRoute: InboxRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  ReportsDistributionRoute: ReportsDistributionRoute,
  ReportsDocumentsRoute: ReportsDocumentsRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  ReportsTrendsRoute: ReportsTrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
